In [ ]:
import pandas as pd
file_path = '/content/payroll_dataset.xlsx'
xls = pd.ExcelFile(file_path)

In [ ]:
# Merge the Employees and Departments tables and display the first 5 rows of the
# merged dataset.
employees_df = pd.read_excel(xls, sheet_name='Employees')
departments_df = pd.read_excel(xls, sheet_name='Departments')
merged_df = pd.merge(employees_df, departments_df, on='DepartmentID')
merged_df.head()

,EmployeeID,Name,DepartmentID,Salary,HireDate,Location,DepartmentName
0,1,Employee 1,D001,6000,2020-01-31,New York,IT
1,5,Employee 5,D001,6400,2020-05-31,New York,IT
2,9,Employee 9,D001,6800,2020-09-30,New York,IT
3,13,Employee 13,D001,7200,2021-01-31,New York,IT
4,17,Employee 17,D001,7600,2021-05-31,New York,IT

In [ ]:
cleaned_df = merged_df.drop_duplicates()
rows_before = merged_df.shape[0]
rows_after = cleaned_df.shape[0]

rows_before, rows_after

(100, 100)

In [ ]:
# Explain and apply the interquartile range (IQR) method to detect and handle outliers in
# the Salary column.
Q1 = cleaned_df['Salary'].quantile(0.25)
Q3 = cleaned_df['Salary'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_removed_df = cleaned_df[(cleaned_df['Salary'] >= lower_bound) & (cleaned_df['Salary'] <= upper_bound)]
rows_before_outlier_removal = cleaned_df.shape[0]
rows_after_outlier_removal = outliers_removed_df.shape[0]

lower_bound, upper_bound, rows_before_outlier_removal, rows_after_outlier_removal

(1050.0, 20850.0, 100, 100)

In [ ]:
# Apply one-hot encoding to the Location column and show the updated dataset.
one_hot_encoded_df = pd.get_dummies(cleaned_df, columns=['Location'])
one_hot_encoded_df

,EmployeeID,Name,DepartmentID,Salary,HireDate,DepartmentName,Location_Chicago,Location_Houston,Location_Los Angeles,Location_New York
0,1,Employee 1,D001,6000,2020-01-31,IT,False,False,False,True
1,5,Employee 5,D001,6400,2020-05-31,IT,False,False,False,True
2,9,Employee 9,D001,6800,2020-09-30,IT,False,False,False,True
3,13,Employee 13,D001,7200,2021-01-31,IT,False,False,False,True
4,17,Employee 17,D001,7600,2021-05-31,IT,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
95,84,Employee 84,D004,14300,2026-12-31,Marketing,False,True,False,False
96,88,Employee 88,D004,14700,2027-04-30,Marketing,False,True,False,False
97,92,Employee 92,D004,15100,2027-08-31,Marketing,False,True,False,False
98,96,Employee 96,D004,15500,2027-12-31,Marketing,False,True,False,False
99,100,Employee 100,D004,15900,2028-04-30,Marketing,False,True,False,False

In [ ]:
# Perform Min-Max normalization on the Salary column and display the transformed
# dataset.
min_salary = cleaned_df['Salary'].min()
max_salary = cleaned_df['Salary'].max()
cleaned_df['Salary_Normalized'] = (cleaned_df['Salary'] - min_salary) / (max_salary - min_salary)
cleaned_df.head()

,EmployeeID,Name,DepartmentID,Salary,HireDate,Location,DepartmentName,Salary_Normalized
0,1,Employee 1,D001,6000,2020-01-31,New York,IT,0.000000
1,5,Employee 5,D001,6400,2020-05-31,New York,IT,0.040404
2,9,Employee 9,D001,6800,2020-09-30,New York,IT,0.080808
3,13,Employee 13,D001,7200,2021-01-31,New York,IT,0.121212
4,17,Employee 17,D001,7600,2021-05-31,New York,IT,0.161616